"use strict";(()=>{var e={};e.id=1996,e.ids=[1996],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},2934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},4580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},5869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},5928:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>x,requestAsyncStorage:()=>l,routeModule:()=>d,serverHooks:()=>m,staticGenerationAsyncStorage:()=>f});var a={};r.r(a),r.d(a,{GET:()=>u,PUT:()=>p});var i=r(9303),s=r(8716),o=r(670),n=r(9692),c=r(7070);async function u(e){let t=await (0,n.e)(),{searchParams:r}=new URL(e.url),a=Number.parseInt(r.get("page")||"1"),i=Number.parseInt(r.get("limit")||"20"),s=(a-1)*i;try{let{data:{user:e},error:r}=await t.auth.getUser();if(r||!e)return c.NextResponse.json({error:"Unauthorized"},{status:401});let{data:a,error:o}=await t.from("notifications").select(`
        id,
        type,
        message,
        is_read,
        created_at,
        profiles:from_user_id (
          username,
          display_name,
          avatar_url
        ),
        posts:post_id (
          id,
          image_url
        )
      `).eq("to_user_id",e.id).order("created_at",{ascending:!1}).range(s,s+i-1);if(o)throw o;return c.NextResponse.json({notifications:a||[]})}catch(e){return console.error("Error fetching notifications:",e),c.NextResponse.json({error:"Failed to fetch notifications"},{status:500})}}async function p(e){let t=await (0,n.e)();try{let{data:{user:r},error:a}=await t.auth.getUser();if(a||!r)return c.NextResponse.json({error:"Unauthorized"},{status:401});let{notification_ids:i}=await e.json(),{error:s}=await t.from("notifications").update({is_read:!0}).eq("to_user_id",r.id).in("id",i||[]);if(s)throw s;return c.NextResponse.json({message:"Notifications marked as read"})}catch(e){return console.error("Error updating notifications:",e),c.NextResponse.json({error:"Failed to update notifications"},{status:500})}}let d=new i.AppRouteRouteModule({definition:{kind:s.x.APP_ROUTE,page:"/api/notifications/route",pathname:"/api/notifications",filename:"route",bundlePath:"app/api/notifications/route"},resolvedPagePath:"C:\\Users\\User-PC\\Desktop\\edna-lifestyle\\app\\api\\notifications\\route.ts",nextConfigOutput:"",userland:a}),{requestAsyncStorage:l,staticGenerationAsyncStorage:f,serverHooks:m}=d,g="/api/notifications/route";function x(){return(0,o.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:f})}},9692:(e,t,r)=>{r.d(t,{e:()=>s});var a=r(7721),i=r(1615);async function s(){let e=await (0,i.cookies)();return(0,a.createServerClient)("https://tdqbdkwokdsudijppjcy.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWJka3dva2RzdWRpanBwamN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTk3NTEsImV4cCI6MjA3MjM5NTc1MX0.ZyW2ggeup_A45cenGjVPFebfVMKwrE6c9NP7xgWLUrU",{cookies:{getAll:()=>e.getAll(),setAll(t){try{t.forEach(({name:t,value:r,options:a})=>e.set(t,r,a))}catch{}}}})}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[9276,9702,5972],()=>r(5928));module.exports=a})();