"use strict";(()=>{var e={};e.id=280,e.ids=[280],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},2934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},4580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},5869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},4996:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>g,patchFetch:()=>f,requestAsyncStorage:()=>p,routeModule:()=>u,serverHooks:()=>m,staticGenerationAsyncStorage:()=>d});var s={};r.r(s),r.d(s,{GET:()=>l});var a=r(9303),i=r(8716),n=r(670),o=r(9692),c=r(7070);async function l(e){let t=await (0,o.e)(),{searchParams:r}=new URL(e.url),s=r.get("q"),a=r.get("type")||"all",i=Number.parseInt(r.get("limit")||"10");if(!s)return c.NextResponse.json({error:"Query parameter is required"},{status:400});try{let e={posts:[],users:[],tags:[]};if("all"===a||"posts"===a){let{data:r}=await t.from("posts").select(`
          id,
          content,
          image_url,
          like_count,
          comment_count,
          view_count,
          created_at,
          profiles:author_id (
            username,
            display_name,
            avatar_url,
            is_verified
          )
        `).textSearch("content",s).order("created_at",{ascending:!1}).limit(i);e.posts=r||[]}if("all"===a||"users"===a){let{data:r}=await t.from("profiles").select("username, display_name, avatar_url, bio, is_verified, follower_count").or(`username.ilike.%${s}%,display_name.ilike.%${s}%`).order("follower_count",{ascending:!1}).limit(i);e.users=r||[]}if("all"===a||"tags"===a){let{data:r}=await t.from("tags").select("id, name, slug, post_count").ilike("name",`%${s}%`).order("post_count",{ascending:!1}).limit(i);e.tags=r||[]}return c.NextResponse.json(e)}catch(e){return console.error("Error performing search:",e),c.NextResponse.json({error:"Search failed"},{status:500})}}let u=new a.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/search/route",pathname:"/api/search",filename:"route",bundlePath:"app/api/search/route"},resolvedPagePath:"C:\\Users\\User-PC\\Desktop\\edna-lifestyle\\app\\api\\search\\route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:p,staticGenerationAsyncStorage:d,serverHooks:m}=u,g="/api/search/route";function f(){return(0,n.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:d})}},9692:(e,t,r)=>{r.d(t,{e:()=>i});var s=r(7721),a=r(1615);async function i(){let e=await (0,a.cookies)();return(0,s.createServerClient)("https://tdqbdkwokdsudijppjcy.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWJka3dva2RzdWRpanBwamN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTk3NTEsImV4cCI6MjA3MjM5NTc1MX0.ZyW2ggeup_A45cenGjVPFebfVMKwrE6c9NP7xgWLUrU",{cookies:{getAll:()=>e.getAll(),setAll(t){try{t.forEach(({name:t,value:r,options:s})=>e.set(t,r,s))}catch{}}}})}}};var t=require("../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),s=t.X(0,[9276,9702,5972],()=>r(4996));module.exports=s})();