"use strict";(()=>{var e={};e.id=5532,e.ids=[5532],e.modules={2885:e=>{e.exports=require("@supabase/supabase-js")},2934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},4580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},5869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},7691:(e,r,t)=>{t.r(r),t.d(r,{originalPathname:()=>m,patchFetch:()=>w,requestAsyncStorage:()=>c,routeModule:()=>p,serverHooks:()=>f,staticGenerationAsyncStorage:()=>d});var s={};t.r(s),t.d(s,{GET:()=>u});var o=t(9303),a=t(8716),n=t(670),i=t(9692),l=t(7070);async function u(e,{params:r}){let{username:t}=await r,s=await (0,i.e)(),{searchParams:o}=new URL(e.url),a=Number.parseInt(o.get("page")||"1"),n=Number.parseInt(o.get("limit")||"20"),u=(a-1)*n;try{let{data:e}=await s.from("profiles").select("id").eq("username",t).single();if(!e)return l.NextResponse.json({error:"User not found"},{status:404});let{data:r,error:o}=await s.from("follows").select(`
        profiles:follower_id (
          username,
          display_name,
          avatar_url,
          bio,
          is_verified,
          follower_count
        )
      `).eq("following_id",e.id).order("created_at",{ascending:!1}).range(u,u+n-1);if(o)throw o;return l.NextResponse.json({followers:r?.map(e=>e.profiles)||[]})}catch(e){return console.error("Error fetching followers:",e),l.NextResponse.json({error:"Failed to fetch followers"},{status:500})}}let p=new o.AppRouteRouteModule({definition:{kind:a.x.APP_ROUTE,page:"/api/users/[username]/followers/route",pathname:"/api/users/[username]/followers",filename:"route",bundlePath:"app/api/users/[username]/followers/route"},resolvedPagePath:"C:\\Users\\User-PC\\Desktop\\edna-lifestyle\\app\\api\\users\\[username]\\followers\\route.ts",nextConfigOutput:"",userland:s}),{requestAsyncStorage:c,staticGenerationAsyncStorage:d,serverHooks:f}=p,m="/api/users/[username]/followers/route";function w(){return(0,n.patchFetch)({serverHooks:f,staticGenerationAsyncStorage:d})}},9692:(e,r,t)=>{t.d(r,{e:()=>a});var s=t(7721),o=t(1615);async function a(){let e=await (0,o.cookies)();return(0,s.createServerClient)("https://tdqbdkwokdsudijppjcy.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWJka3dva2RzdWRpanBwamN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTk3NTEsImV4cCI6MjA3MjM5NTc1MX0.ZyW2ggeup_A45cenGjVPFebfVMKwrE6c9NP7xgWLUrU",{cookies:{getAll:()=>e.getAll(),setAll(r){try{r.forEach(({name:r,value:t,options:s})=>e.set(r,t,s))}catch{}}}})}}};var r=require("../../../../../webpack-runtime.js");r.C(e);var t=e=>r(r.s=e),s=r.X(0,[9276,9702,5972],()=>t(7691));module.exports=s})();